microstrain_inertial_driver:
  ros__parameters:
    # Copy this file to a new file, fill out this section with desired parameters, and specify the new file via params_file to override the default params
    filter_use_compensated_accel: False
    imu_raw_data_rate: 100.0
    filter_imu_data_rate: 100.0
    use_enu_frame: True
    filter_use_compensated_accel: False